### ISSUE TITLE
gwoptics.jar too new for Mac OS X version of Processing

### ISSUE THREAD

**Issue by jooray** [OpenBCI/OpenBCI_Processing#33]
This commit:

https://github.com/OpenBCI/OpenBCI_Processing/commit/1257bbf6f9f99a6b0e81afbe15e5417c24700544

added a new version of gwoptics.jar file, which does not work on Mac OS X. The version of Java bundled with OS X version of Processing is too old to read this jarfile, it has classes compiled for Java 1.8.

Note: It does not matter what version of Java is installed in OS X itself, Processing for Mac OS X bundles an internal Java version.

I don't know what this commit supposed to fix, but it broke this app for Mac OS X completely, it does not even run.

**Comment by pushtheworldllc** [comment]
Is this the same error?

```


No library found for org.gwoptics.graphics
No library found for org.gwoptics.graphics.graph2D
No library found for org.gwoptics.graphics.graph2D
No library found for org.gwoptics.graphics.graph2D
No library found for org.gwoptics.graphics.graph2D.traces
No library found for org.gwoptics.graphics.graph2D.backgrounds
No library found for org.gwoptics.graphics
No library found for org.gwoptics.graphics.graph2D
No library found for org.gwoptics.graphics.graph2D
No library found for org.gwoptics.graphics.graph2D
No library found for org.gwoptics.graphics.graph2D.traces
No library found for org.gwoptics.graphics.graph2D.backgrounds
Libraries must be installed in a folder named 'libraries' inside the 'sketchbook' folder.
```

**Comment by teonbrooks** [comment]
@jooray, have you tried the packaged GUI app? if it doesn't open, it could be a security issue, and that can be resolved by accepting unidentified developers in your system preferences > security
