### ISSUE TITLE
redirect to openbci_gui?

### ISSUE THREAD

**Issue by micuat** [OpenBCI/OpenBCI_Processing#51]
Hi, this may sound stupid but the repository openbci_processing and openbci_gui are very confusing. I guess this one is obsolete, but the descriptions says "Repository containing the latest OpenBCI Processing GUI." I think you should change the description and add a line in the readme to redirect people to https://github.com/OpenBCI/OpenBCI_GUI.

**Comment by jnaulty** [comment]
@aj-ptw  @conorrussomanno 
@micuat 's suggestion is valid.
This repo should get marked as [DEPRECATED] and redirect to [OpenBCI_GUI](https://github.com/OpenBCI/OpenBCI_GUI) ;)

**Comment by andrewjaykeller** [comment]
THANKS!
